name: 05 - Matrix Strategies

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
  test-on-all-os:
    runs-on: ${{ matrix.os }}  # <--- Yahan magic hai
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # 3 alag computers!
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Print OS Name
        run: echo "Hello from ${{ matrix.os }}"
